import { Pokemon } from './pokemon';

export const PokemonList: Pokemon[] = [
  { name: 'Bulbasaur', type: 'Grass/Poison', imgPath: './assets/bulbasaur.png' },
  { name: 'Ivysaur', type: 'Grass/Poison', imgPath: './assets/ivysaur.png' },
  { name: 'Venusaur', type: 'Grass/Poison', imgPath: './assets/venusaur.png' },
  { name: 'Charmander', type: 'Fire', imgPath: './assets/charmander.png' },
  { name: 'Charmeleon', type: 'Fire', imgPath: './assets/charmeleon.png' },
  { name: 'Charizard', type: 'Fire/Flying', imgPath: './assets/charizard.png' },
  { name: 'Squirtle', type: 'Water', imgPath: './assets/squirtle.png' },
  { name: 'Wartortle', type: 'Water', imgPath: './assets/wartortle.png' },
  { name: 'Blastoise', type: 'Water', imgPath: './assets/blastoise.png' },
  { name: 'Caterpie', type: 'Bug', imgPath: './assets/caterpie.png' },
  { name: 'Metapod', type: 'Bug', imgPath: './assets/metapod.png' },
  { name: 'Butterfree', type: 'Bug/Flying', imgPath: './assets/butterfree-f.png' },
  { name: 'Weedle', type: 'Bug/Poison', imgPath: './assets/weedle.png' },
  { name: 'Kakuna', type: 'Bug/Poison', imgPath: './assets/kakuna.png' },
  { name: 'Beedrill', type: 'Bug/Poison', imgPath: './assets/beedrill.png' },
  { name: 'Pidgey', type: 'Normal/Flying', imgPath: './assets/pidgey.png' },
  { name: 'Pidgeotto', type: 'Normal/Flying', imgPath: './assets/pidgeotto.png' },
  { name: 'Pidgeot', type: 'Normal/Flying', imgPath: './assets/pidgeot.png' },
  { name: 'Rattata', type: 'Normal', imgPath: './assets/rattata-f.png' },
  { name: 'Raticate', type: 'Normal', imgPath: './assets/raticate-f.png' },
  { name: 'Spearow', type: 'Normal/Flying', imgPath: './assets/spearow.png' },
  { name: 'Fearow', type: 'Normal/Flying', imgPath: './assets/fearow.png' },
  { name: 'Ekans', type: 'Poison', imgPath: './assets/ekans.png' },
  { name: 'Arbok', type: 'Poison', imgPath: './assets/arbok.png' },
  { name: 'Pikachu', type: 'Electric', imgPath: './assets/pikachu-f.png' },
  { name: 'Raichu', type: 'Electric', imgPath: './assets/raichu-f.png' },
  { name: 'Sandshrew', type: 'Ground', imgPath: './assets/sandshrew.png' },
  { name: 'Sandslash', type: 'Ground', imgPath: './assets/sandslash.png' },
  { name: 'Nidoran', type: 'Poison', imgPath: './assets/nidoran-f.png' },
  { name: 'Nidorina', type: 'Poison', imgPath: './assets/nidorina.png' }
];